
export enum MainActionTypes {
    INITWEEKLYPLAYLIST= "INITWEEKLYPLAYLIST",
    INITWEEKLYARTIST= "INITWEEKLYARTIST",
    INITWEEKLYSONGSPLAYLIST= "INITWEEKLYSONGSPLAYLIST",
    MAIN_WAITING= "MAIN_WAITING",
    MAIN_ERROR= "MAIN_ERROR",
    MAINCLEAR= "MAINCLEAR",
}